version: '2'
services:

  #RabbitMQ broker, for Celery
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.7.3
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  #Flower UI for Celery queue
  ui:
    build: ./celery-ib
    command: flower -A celery_tutorial.celery_app --port=5555 --broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit --auto_refresh=True --loglevel="DEBUG"
    environment:
      - BROKER=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit
    volumes:
      - ./celery_tutorial:/celery_tutorial
      - ./ibapi:/ibapi
    ports:
        - "127.0.0.1:5010:5555"
    links:
        - rabbit
    depends_on:
        - rabbit
#    restart: always

  #Python Celery worker
  worker-1:
    build: ./celery-ib
#    command: celery -A worker -l "DEBUG" -Ofair --concurrency=1
#    command:  celery -A celery_tutorial.celery_app worker -l "DEBUG" -0fair --concurrency=1
    command:  celery -A celery_tutorial.celery_app worker -l "DEBUG"
    restart: on-failure
    environment:
      - BROKER=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit
      - ECHEANCE_CAC40=${ECHEANCE_CAC40}
      - ECHEANCE_DAX=${ECHEANCE_DAX}
      - ECHEANCE_EUROSTOXX=${ECHEANCE_EUROSTOXX}
      - ECHEANCE_FTSEMIB=${ECHEANCE_FTSEMIB}
    volumes:
      - ./celery_tutorial:/celery_tutorial
      - ./ibapi:/ibapi
      - ./logs:/logs
    links:
      - tws:tws

  #Celery beat, to schedule periodic tasks
  beat:
    build: ./celery-ib
    command: celery -A celery_tutorial.celery_app beat -l "DEBUG"
    restart: on-failure
    environment:
      - BROKER=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit
    links:
        - rabbit
    depends_on:
        - mysql
        - rabbit
    volumes:
      - ./celery_tutorial:/celery_tutorial
      - ./ibapi:/ibapi

  #Interactive Broker containerized API
  tws:
    build: ./ib-docker
    ports:
      - "4003:4003"
      - "5901:5900"
    volumes:
      - ./ib-docker/ib/IBController.ini:/root/IBController/IBController.ini
      - ./ib-docker/ib/jts.ini:/root/Jts/jts.ini
    restart: on-failure
    environment:
      - TZ=America/Chicago
      # Variables pulled from /IBController/IBControllerGatewayStart.sh
      - VNC_PASSWORD=password # CHANGEME
      - TWS_MAJOR_VRSN=974
      - IBC_INI=/root/IBController/IBController.ini
      - IBC_PATH=/opt/IBController
      - TWS_PATH=/root/Jts
      - TWS_CONFIG_PATH=/root/Jts
      - LOG_PATH=/opt/IBController/Logs
      - JAVA_PATH=/opt/i4j_jres/1.8.0_152/bin # JRE is bundled starting with TWS 952 
      - TRADING_MODE=paper # either paper or live
      - TWSUSERID=schran892 # IB account
      - TWSPASSWORD=Quant1984! # IB account password
      - FIXUSERID=
      - FIXPASSWORD=
      - APP=GATEWAY

  "tws-gui":
    image: alekna/ib-tws
    environment:
      - TZ=America/Chicago
    logging:
      driver: "none"
    ports:
      - "5904:5900"

  mysql:
    image: mysql:5.7
    ports:
      - "3309:3306"
    command: --init-file /data/application/init.sql
    volumes:
#      - ./mysqldata:/var/lib/data
      - ./db/init.sql:/data/application/init.sql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
#      MYSQL_USER: root
      MYSQL_TAGS: dev
      SERVICE_NAME: mysql

  #Database web client
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: trading
    restart: always
    ports:
      - 8081:80

  #Grafana to explore and visualise data
  grafana:
    image: grafana/grafana:5.0.3
    restart: always
    ports:
        - "127.0.0.1:7000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
